;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        helm-M-x
        indent-for-tab-command
        python-nav-forward-block
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ))
