;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        helm-M-x
        indent-for-tab-command
        iy-go-to-char--command
        python-nav-forward-block
        wdired-finish-edit
        zzz-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        dired-do-rename
        helm-occur
        ))
